import Head from 'next/head';
import Link from 'next/link';

import { FC, PropsWithChildren } from 'react';
import { IconLinkedin } from '../icons';
import { Navbar } from '../navbar/Navbar';

import { Footer, Header, SectionRigth, SectionLefth } from './layoutStyled';

interface Props {
	title?: string;
}
export const Layout: FC<PropsWithChildren<Props>> = ({ children, title }) => {
	return (
		<>
			<Head>
				<title>{title || 'Portafolio'}</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link
					rel="icon"
					href="/icons/program (2).png"
				/>
			</Head>
			<Header>
				<Navbar />
			</Header>
			<div>{children}</div>
			<Footer>
				<div>
					<SectionLefth>
						<p>Pagina creada por Eduardo Padrino</p>
					</SectionLefth>
					<SectionRigth>
						<section>
							<Link
								href="https://www.linkedin.com/in/eduardo-padrino-b40238257/"
								target="_blank"
							>
								<IconLinkedin
									width="100%"
									height="100%"
								/>
							</Link>
						</section>
					</SectionRigth>
				</div>
			</Footer>
		</>
	);
};
